# Generated by Django 4.2.7 on 2025-11-30 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("personas", "0002_agente_agenterol_agrupacion_area_rol_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        default="media",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("reportada", "Reportada"),
                            ("en_revision", "En Revisión"),
                            ("en_proceso", "En Proceso"),
                            ("resuelta", "Resuelta"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="reportada",
                        max_length=30,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_asignacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_resolucion", models.DateTimeField(blank=True, null=True)),
                ("resolucion", models.TextField(blank=True, null=True)),
                ("comentarios_seguimiento", models.JSONField(blank=True, default=list)),
                (
                    "area_involucrada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidencias",
                        to="personas.area",
                    ),
                ),
                (
                    "asignado_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidencias_asignadas",
                        to="personas.agente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidencias_creadas",
                        to="personas.agente",
                    ),
                ),
            ],
            options={
                "db_table": "incidencia",
                "ordering": ["-fecha_creacion"],
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["estado"], name="incidencia_estado_0a4e05_idx"
                    ),
                    models.Index(
                        fields=["creado_por"], name="incidencia_creado__913b3b_idx"
                    ),
                    models.Index(
                        fields=["asignado_a"], name="incidencia_asignad_9f5c96_idx"
                    ),
                    models.Index(
                        fields=["area_involucrada"],
                        name="incidencia_area_in_5d4f2b_idx",
                    ),
                    models.Index(
                        fields=["fecha_creacion"], name="incidencia_fecha_c_357412_idx"
                    ),
                ],
            },
        ),
    ]
