# Generated by Django 5.2.8 on 2025-12-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('NUEVA', 'Nueva'), ('ASIGNADA', 'Asignada'), ('EN_PROGRESO', 'En Progreso'), ('CERRADA', 'Cerrada')], default='NUEVA', max_length=30),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20),
        ),
    ]
