# Generated by Django 5.2.8 on 2025-12-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_alter_incidencia_estado_alter_incidencia_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_PROGRESO', 'En Progreso'), ('RESUELTA', 'Resuelta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=30),
        ),
    ]
