# Generated by Django 5.2.8 on 2025-12-02 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_alter_incidencia_estado'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='incidencia',
            name='incidencia_estado_0a4e05_idx',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='prioridad',
        ),
    ]
