# Generated by Django 5.2.9 on 2025-12-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0004_remove_incidencia_incidencia_estado_0a4e05_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('en_proceso', 'En Proceso'), ('pendiente_informacion', 'Pendiente de Información'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada')], default='abierta', max_length=25),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10),
        ),
    ]
