# Generated by Django 5.2.9 on 2025-12-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0005_add_estado_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('en_proceso', 'En Proceso'), ('pendiente_informacion', 'Información Pendiente'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada')], default='abierta', max_length=25),
        ),
    ]
