# Generated by Django 4.2.7 on 2025-12-04 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incidencias", "0006_alter_incidencia_estado"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incidencia",
            options={"managed": False, "ordering": ["-fecha_creacion"]},
        ),
    ]
