# Generated by Django 4.2.7 on 2025-11-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auditoria",
            fields=[
                (
                    "id_auditoria",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("pk_afectada", models.BigIntegerField(blank=True, null=True)),
                (
                    "nombre_tabla",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("creado_en", models.DateTimeField(blank=True, null=True)),
                ("valor_previo", models.JSONField(blank=True, null=True)),
                ("valor_nuevo", models.JSONField(blank=True, null=True)),
                ("accion", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "auditoria",
                "managed": False,
            },
        ),
    ]
