# Generated by Django 5.2.7 on 2025-10-20 21:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('contenido', models.BinaryField()),
                ('tipo', models.CharField(max_length=100)),
                ('tamaño', models.BigIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'db_table': 'archivos',
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('archivo_ruta', models.FileField(upload_to='convenios/')),
                ('hash', models.CharField(max_length=64)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('OBSOLETO', 'Obsoleto')], default='VIGENTE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Convenio',
                'verbose_name_plural': 'Convenios',
                'db_table': 'convenios',
            },
        ),
        migrations.CreateModel(
            name='RespuestaConCitas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('respuesta', models.TextField()),
                ('citas', models.JSONField()),
                ('confianza', models.DecimalField(decimal_places=4, max_digits=5)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Respuesta con Citas',
                'verbose_name_plural': 'Respuestas con Citas',
                'db_table': 'respuestas_con_citas',
            },
        ),
        migrations.CreateModel(
            name='ResultadoBusqueda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resultados', models.JSONField()),
                ('relevancia', models.DecimalField(decimal_places=4, max_digits=5)),
                ('tiempo', models.DurationField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resultado de Búsqueda',
                'verbose_name_plural': 'Resultados de Búsqueda',
                'db_table': 'resultados_busqueda',
            },
        ),
        migrations.CreateModel(
            name='ConsultaConvenio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('citas', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_convenio', to='personas.agente')),
            ],
            options={
                'verbose_name': 'Consulta de Convenio',
                'verbose_name_plural': 'Consultas de Convenio',
                'db_table': 'consultas_convenio',
            },
        ),
        migrations.CreateModel(
            name='IndiceConvenio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metodo', models.CharField(choices=[('BM25', 'BM25'), ('EMBEDDINGS', 'Embeddings')], max_length=20)),
                ('hash_indice', models.CharField(max_length=64)),
                ('construido_en', models.DateTimeField(auto_now_add=True)),
                ('version_motor', models.CharField(max_length=50)),
                ('convenio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indice', to='convenio_ia.convenio')),
            ],
            options={
                'verbose_name': 'Índice de Convenio',
                'verbose_name_plural': 'Índices de Convenio',
                'db_table': 'indices_convenio',
            },
        ),
    ]
