# Generated by Django 4.2.7 on 2025-11-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id_asistencia",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("fecha", models.DateField()),
                ("hora_entrada", models.TimeField(blank=True, null=True)),
                ("hora_salida", models.TimeField(blank=True, null=True)),
                ("marcacion_entrada_automatica", models.BooleanField(default=False)),
                ("marcacion_salida_automatica", models.BooleanField(default=False)),
                ("es_correccion", models.BooleanField(default=False)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "asistencia",
                "ordering": ["-fecha", "-hora_entrada"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IntentoMarcacionFraudulenta",
            fields=[
                ("id_intento", models.BigAutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                ("dni_ingresado", models.CharField(max_length=20)),
                ("tipo_intento", models.CharField(max_length=50)),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "intento_marcacion_fraudulenta",
                "ordering": ["-fecha", "-hora"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Licencia",
            fields=[
                ("id_licencia", models.BigAutoField(primary_key=True, serialize=False)),
                ("estado", models.CharField(default="pendiente", max_length=50)),
                ("fecha_desde", models.DateField()),
                ("fecha_hasta", models.DateField()),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("justificacion", models.TextField(blank=True, null=True)),
                ("fecha_aprobacion", models.DateField(blank=True, null=True)),
                ("observaciones_aprobacion", models.TextField(blank=True, null=True)),
                ("fecha_rechazo", models.DateField(blank=True, null=True)),
                ("motivo_rechazo", models.TextField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "licencia",
                "ordering": ["-creado_en"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ParteDiario",
            fields=[
                (
                    "id_parte_diario",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("fecha_parte", models.DateField()),
                ("creado_en", models.DateTimeField(blank=True, null=True)),
                ("actualizado_en", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "parte_diario",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoLicencia",
            fields=[
                (
                    "id_tipo_licencia",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "tipo_licencia",
                "managed": False,
            },
        ),
    ]
