# Generated by Django 5.2.7 on 2025-10-20 21:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLicencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParteDiario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha_parte', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('anulado', 'Anulado')], default='borrador', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_actualizados', to=settings.AUTH_USER_MODEL)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.agente')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.area')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_creados', to=settings.AUTH_USER_MODEL)),
                ('tipo_licencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.tipolicencia')),
            ],
            options={
                'indexes': [models.Index(fields=['area', 'fecha_parte', 'agente'], name='asistencia__area_id_4cbcd6_idx')],
            },
        ),
    ]
