# Generated by Django 5.2.7 on 2025-10-24 19:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('personas', '0003_usuario_actualizado_por_usuario_password_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partediario',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='partediario',
            name='tipo_licencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asistencia.tipolicencia'),
        ),
        migrations.AlterUniqueTogether(
            name='partediario',
            unique_together={('fecha_parte', 'agente')},
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('archivo', models.FileField(upload_to='adjuntos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('nombre_original', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('tamaño', models.BigIntegerField()),
                ('tipo_archivo', models.CharField(max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asistencia_adjunto',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='asistencia__content_7fcfb8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('con_goce_haberes', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.agente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creadas', to=settings.AUTH_USER_MODEL)),
                ('tipo_licencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.tipolicencia')),
            ],
            options={
                'db_table': 'asistencia_licencia',
                'indexes': [models.Index(fields=['agente', 'fecha_inicio', 'fecha_fin'], name='asistencia__agente__d5ea19_idx'), models.Index(fields=['tipo_licencia', 'estado'], name='asistencia__tipo_li_590053_idx')],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcas_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='personas.agente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['agente', 'fecha', 'hora'], name='asistencia__agente__68046a_idx')],
                'unique_together': {('agente', 'fecha', 'hora', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_novedad', models.CharField(choices=[('medica', 'Médica'), ('familiar', 'Familiar'), ('capacitacion', 'Capacitación'), ('otra', 'Otra')], max_length=20)),
                ('requiere_justificativo', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.agente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asistencia_novedad',
                'indexes': [models.Index(fields=['agente', 'fecha_inicio', 'fecha_fin'], name='asistencia__agente__e1532d_idx'), models.Index(fields=['tipo_novedad', 'estado'], name='asistencia__tipo_no_d706b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParametrosControlHorario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ventana_entrada_inicio', models.TimeField(help_text='Hora más temprana permitida para marcar entrada')),
                ('ventana_entrada_fin', models.TimeField(help_text='Hora más tardía permitida para marcar entrada')),
                ('ventana_salida_inicio', models.TimeField(help_text='Hora más temprana permitida para marcar salida')),
                ('ventana_salida_fin', models.TimeField(help_text='Hora más tardía permitida para marcar salida')),
                ('tolerancia_entrada_min', models.IntegerField(default=15, help_text='Tolerancia entrada en minutos')),
                ('tolerancia_salida_min', models.IntegerField(default=15, help_text='Tolerancia salida en minutos')),
                ('requiere_justificacion_fuera_ventana', models.BooleanField(default=True)),
                ('horas_trabajo_por_dia', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametros_actualizados', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_horario', to='personas.area')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametros_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asistencia_parametros_control_horario',
                'indexes': [models.Index(fields=['area', 'vigente_desde', 'vigente_hasta'], name='asistencia__area_id_123254_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ventana_entrada_fin__gt', models.F('ventana_entrada_inicio'))), name='ventana_entrada_valida'), models.CheckConstraint(condition=models.Q(('ventana_salida_fin__gt', models.F('ventana_salida_inicio'))), name='ventana_salida_valida'), models.CheckConstraint(condition=models.Q(('vigente_hasta__isnull', True), ('vigente_hasta__gt', models.F('vigente_desde')), _connector='OR'), name='vigencia_valida')],
            },
        ),
    ]
