# Generated by Django 5.2.7 on 2025-10-25 21:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_partediario_actualizado_en_and_more'),
        ('personas', '0004_add_password_reset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('horario_entrada', models.TimeField(blank=True, null=True)),
                ('horario_salida', models.TimeField(blank=True, null=True)),
                ('minutos_tarde', models.IntegerField(default=0)),
                ('minutos_extras', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('tardanza', 'Tardanza'), ('licencia', 'Licencia')], default='presente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='personas.agente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asistencia_asistencia',
                'indexes': [models.Index(fields=['agente', 'fecha'], name='asistencia__agente__050a12_idx'), models.Index(fields=['estado', 'fecha'], name='asistencia__estado_6ddd7f_idx')],
                'unique_together': {('agente', 'fecha')},
            },
        ),
    ]
