# Generated by Django 4.2 on 2025-11-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organigrama',
            fields=[
                ('id_organigrama', models.BigAutoField(primary_key=True)),
                ('nombre', models.CharField(max_length=200)),
                ('estructura', models.JSONField()),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.CharField(default='Sistema', max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organigrama',
                'ordering': ['-actualizado_en'],
                'managed': True,
            },
        ),
    ]