# Generated by Django 5.2.7 on 2025-10-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cuil',
            field=models.CharField(blank=True, help_text='CUIL sin guiones (11 dígitos)', max_length=11, null=True, unique=True),
        ),
    ]
