# Generated by Django 4.2.7 on 2025-11-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agente",
            fields=[
                ("id_agente", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("dni", models.CharField(max_length=20, unique=True)),
                ("cuil", models.CharField(max_length=20, unique=True)),
                ("legajo", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("password_hash", models.CharField(max_length=255)),
                ("telefono", models.CharField(blank=True, max_length=15, null=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("provincia", models.CharField(blank=True, max_length=100, null=True)),
                ("ciudad", models.CharField(blank=True, max_length=100, null=True)),
                ("calle", models.CharField(blank=True, max_length=150, null=True)),
                ("numero", models.CharField(blank=True, max_length=10, null=True)),
                ("creado_en", models.DateTimeField(blank=True, null=True)),
                ("actualizado_en", models.DateTimeField(blank=True, null=True)),
                ("horario_entrada", models.TimeField(blank=True, null=True)),
                ("horario_salida", models.TimeField(blank=True, null=True)),
                ("agrupacion", models.CharField(blank=True, max_length=100, null=True)),
                ("activo", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "agente",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AgenteRol",
            fields=[
                (
                    "id_agente_rol",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("asignado_en", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(blank=True, null=True)),
                ("actualizado_en", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "agente_rol",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Agrupacion",
            fields=[
                (
                    "id_agrupacion",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("color", models.CharField(default="#e79043", max_length=7)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(blank=True, null=True)),
                ("actualizado_en", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "agrupacion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id_area", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("nivel", models.IntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(blank=True, null=True)),
                ("actualizado_en", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "area",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                ("id_rol", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(blank=True, null=True)),
                ("actualizado_en", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "rol",
                "managed": False,
            },
        ),
        migrations.AlterField(
            model_name="organigrama",
            name="id_organigrama",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
