# Generated by Django 5.2.9 on 2025-12-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_agente_agenterol_agrupacion_area_rol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionActiva',
            fields=[
                ('id_sesion_activa', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=100, null=True)),
                ('navegador', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sesion_activa',
                'ordering': ['creado_en'],
                'managed': False,
            },
        ),
    ]
