# Generated by Django 5.2.7 on 2025-10-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_usuario_actualizado_por_usuario_password_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password_reset',
            field=models.BooleanField(default=False, help_text='Indica si la contraseña fue reseteada automáticamente'),
        ),
    ]
