# Generated by Django 5.2.7 on 2025-10-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_add_password_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
