# Generated by Django 4.2.7 on 2025-11-23 18:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cronograma",
            fields=[
                (
                    "id_cronograma",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("fecha_aprobacion", models.DateField(blank=True, null=True)),
                ("tipo", models.CharField(blank=True, max_length=50, null=True)),
                ("hora_fin", models.TimeField(blank=True, null=True)),
                ("hora_inicio", models.TimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(blank=True, null=True)),
                ("actualizado_en", models.DateTimeField(blank=True, null=True)),
                ("estado", models.CharField(blank=True, max_length=50, null=True)),
                ("fecha_creacion", models.DateField(blank=True, null=True)),
                (
                    "creado_por_rol",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "cronograma",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Feriado",
            fields=[
                ("id_feriado", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("es_nacional", models.BooleanField(default=False)),
                ("es_provincial", models.BooleanField(default=False)),
                ("es_local", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "feriado",
                "ordering": ["fecha_inicio", "fecha_fin", "nombre"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Guardia",
            fields=[
                ("id_guardia", models.BigAutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("creado_en", models.DateTimeField(blank=True, null=True)),
                ("actualizado_en", models.DateTimeField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("tipo", models.CharField(blank=True, max_length=50, null=True)),
                ("activa", models.BooleanField(blank=True, null=True)),
                ("estado", models.CharField(blank=True, max_length=50, null=True)),
                ("horas_planificadas", models.IntegerField(blank=True, null=True)),
                ("horas_efectivas", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "guardia",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HoraCompensacion",
            fields=[
                (
                    "id_hora_compensacion",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "fecha_servicio",
                    models.DateField(help_text="Fecha en que se prestó el servicio"),
                ),
                (
                    "hora_inicio_programada",
                    models.TimeField(
                        help_text="Hora de inicio programada de la guardia"
                    ),
                ),
                (
                    "hora_fin_programada",
                    models.TimeField(help_text="Hora de fin programada de la guardia"),
                ),
                (
                    "hora_fin_real",
                    models.TimeField(
                        help_text="Hora real de finalización del servicio"
                    ),
                ),
                (
                    "horas_programadas",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Horas programadas originalmente",
                        max_digits=4,
                    ),
                ),
                (
                    "horas_efectivas",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Horas realmente trabajadas",
                        max_digits=4,
                    ),
                ),
                (
                    "horas_extra",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Horas extra trabajadas",
                        max_digits=4,
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("siniestro", "Siniestro/Accidente"),
                            ("emergencia", "Emergencia Operativa"),
                            ("operativo", "Operativo Especial"),
                            ("refuerzo", "Refuerzo de Seguridad"),
                            ("otro", "Otro Motivo"),
                        ],
                        default="emergencia",
                        max_length=20,
                    ),
                ),
                (
                    "descripcion_motivo",
                    models.TextField(
                        help_text="Descripción detallada del motivo de la extensión"
                    ),
                ),
                (
                    "numero_acta",
                    models.CharField(
                        blank=True,
                        help_text="Número de acta o expediente relacionado",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de Aprobación"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                            ("pagada", "Pagada/Compensada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "tipo_compensacion",
                    models.CharField(
                        choices=[
                            ("pago", "Pago Adicional"),
                            ("franco", "Franco Compensatorio"),
                            ("plus", "Plus Adicional"),
                        ],
                        default="plus",
                        max_length=20,
                    ),
                ),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                ("observaciones_aprobacion", models.TextField(blank=True, null=True)),
                (
                    "valor_hora_extra",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor por hora extra calculado",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "monto_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monto total de compensación",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hora_compensacion",
                "ordering": ["-fecha_servicio", "-creado_en"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NotaGuardia",
            fields=[
                ("id_nota", models.BigAutoField(primary_key=True, serialize=False)),
                ("nota", models.TextField(blank=True, null=True)),
                ("fecha_nota", models.DateTimeField(auto_now_add=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "nota_guardia",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ParametrosArea",
            fields=[
                (
                    "id_parametros_area",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("ventana_entrada_inicio", models.TimeField(default="07:30:00")),
                ("ventana_entrada_fin", models.TimeField(default="09:00:00")),
                ("ventana_salida_inicio", models.TimeField(default="16:00:00")),
                ("ventana_salida_fin", models.TimeField(default="18:30:00")),
                ("tolerancia_entrada_min", models.IntegerField(default=15)),
                ("tolerancia_salida_min", models.IntegerField(default=15)),
                (
                    "horas_trabajo_dia",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("8.0"), max_digits=4
                    ),
                ),
                ("vigente_desde", models.DateField()),
                ("vigente_hasta", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(blank=True, null=True)),
                ("actualizado_en", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "parametros_area",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReglaPlus",
            fields=[
                (
                    "id_regla_plus",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "horas_minimas_diarias",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("8.0"), max_digits=5
                    ),
                ),
                (
                    "horas_minimas_mensuales",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("160.0"), max_digits=6
                    ),
                ),
                (
                    "porcentaje_plus",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("20.0"), max_digits=5
                    ),
                ),
                ("aplica_areas_operativas", models.BooleanField(default=True)),
                ("aplica_areas_administrativas", models.BooleanField(default=False)),
                ("vigente_desde", models.DateField()),
                ("vigente_hasta", models.DateField(blank=True, null=True)),
                ("activa", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(blank=True, null=True)),
                ("actualizado_en", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "reglas_plus",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ResumenGuardiaMes",
            fields=[
                (
                    "id_resumen_guardia_mes",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("mes", models.IntegerField()),
                ("anio", models.IntegerField()),
                ("plus20", models.BooleanField(blank=True, null=True)),
                ("plus40", models.BooleanField(blank=True, null=True)),
                ("total_horas_guardia", models.IntegerField(blank=True, null=True)),
                (
                    "horas_efectivas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.0"),
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "porcentaje_plus",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.0"),
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "monto_calculado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "estado_plus",
                    models.CharField(
                        blank=True, default="pendiente", max_length=30, null=True
                    ),
                ),
                ("fecha_calculo", models.DateTimeField(blank=True, null=True)),
                ("aprobado_en", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "resumen_guardia_mes",
                "managed": False,
            },
        ),
    ]
