# Generated by Django 5.2.7 on 2025-10-24 19:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardias', '0001_initial'),
        ('personas', '0003_usuario_actualizado_por_usuario_password_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaPlus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('horas_minimas_diarias', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('horas_minimas_mensuales', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('aplica_areas_operativas', models.BooleanField(default=True)),
                ('aplica_areas_administrativas', models.BooleanField(default=True)),
                ('porcentaje_plus', models.DecimalField(decimal_places=2, help_text='Ej: 20.00 para 20%, 40.00 para 40%', max_digits=5)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_plus_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_plus_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guardias_regla_plus',
            },
        ),
        migrations.CreateModel(
            name='HorasGuardias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('horas_planificadas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('horas_efectivas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('guardias_totales', models.IntegerField(default=0)),
                ('guardias_cumplidas', models.IntegerField(default=0)),
                ('plus_aplicable', models.BooleanField(default=False)),
                ('porcentaje_plus', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumenes_horas_actualizados', to=settings.AUTH_USER_MODEL)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumen_horas_guardias', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.area')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumenes_horas_creados', to=settings.AUTH_USER_MODEL)),
                ('regla_plus_aplicada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guardias.reglaplus')),
            ],
            options={
                'db_table': 'guardias_horas_guardias',
            },
        ),
        migrations.CreateModel(
            name='AsignacionPlus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('porcentaje_aplicado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_plus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('calculado', 'Calculado'), ('aprobado', 'Aprobado'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='calculado', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_plus_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_plus', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_plus_creadas', to=settings.AUTH_USER_MODEL)),
                ('resumen_horas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_plus', to='guardias.horasguardias')),
                ('regla_plus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guardias.reglaplus')),
            ],
            options={
                'db_table': 'guardias_asignacion_plus',
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('es_nacional', models.BooleanField(default=True)),
                ('es_provincial', models.BooleanField(default=False)),
                ('es_local', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feriados_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feriados_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guardias_feriado',
                'indexes': [models.Index(fields=['fecha'], name='guardias_fe_fecha_1fdbc7_idx'), models.Index(fields=['es_nacional', 'es_provincial', 'es_local'], name='guardias_fe_es_naci_9a495a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reglaplus',
            index=models.Index(fields=['vigente_desde', 'vigente_hasta', 'activa'], name='guardias_re_vigente_51cfb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='reglaplus',
            constraint=models.CheckConstraint(condition=models.Q(('vigente_hasta__isnull', True), ('vigente_hasta__gt', models.F('vigente_desde')), _connector='OR'), name='vigencia_regla_plus_valida'),
        ),
        migrations.AddConstraint(
            model_name='reglaplus',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_plus__gte', 0), ('porcentaje_plus__lte', 100)), name='porcentaje_plus_valido'),
        ),
        migrations.AddIndex(
            model_name='horasguardias',
            index=models.Index(fields=['agente', 'año', 'mes'], name='guardias_ho_agente__ef8478_idx'),
        ),
        migrations.AddIndex(
            model_name='horasguardias',
            index=models.Index(fields=['area', 'año', 'mes'], name='guardias_ho_area_id_a33a44_idx'),
        ),
        migrations.AddConstraint(
            model_name='horasguardias',
            constraint=models.CheckConstraint(condition=models.Q(('mes__gte', 1), ('mes__lte', 12)), name='mes_valido'),
        ),
        migrations.AddConstraint(
            model_name='horasguardias',
            constraint=models.CheckConstraint(condition=models.Q(('año__gte', 2020)), name='año_valido'),
        ),
        migrations.AddConstraint(
            model_name='horasguardias',
            constraint=models.CheckConstraint(condition=models.Q(('guardias_cumplidas__lte', models.F('guardias_totales'))), name='guardias_cumplidas_validas'),
        ),
        migrations.AlterUniqueTogether(
            name='horasguardias',
            unique_together={('agente', 'area', 'año', 'mes')},
        ),
        migrations.AddIndex(
            model_name='asignacionplus',
            index=models.Index(fields=['agente', 'estado'], name='guardias_as_agente__089424_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionplus',
            index=models.Index(fields=['resumen_horas', 'estado'], name='guardias_as_resumen_cc6b9b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionplus',
            unique_together={('agente', 'resumen_horas', 'regla_plus')},
        ),
    ]
