# Generated by Django 5.2.7 on 2025-10-20 21:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guardias', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaCorreo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('asunto_tpl', models.CharField(max_length=500)),
                ('cuerpo_tpl', models.TextField()),
                ('variables', models.JSONField()),
                ('version', models.IntegerField(default=1)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Correo',
                'verbose_name_plural': 'Plantillas de Correo',
                'db_table': 'plantillas_correo',
            },
        ),
        migrations.CreateModel(
            name='RenderCorreo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=500)),
                ('cuerpo', models.TextField()),
                ('variables', models.JSONField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Correo Renderizado',
                'verbose_name_plural': 'Correos Renderizados',
                'db_table': 'render_correos',
            },
        ),
        migrations.CreateModel(
            name='Vista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datos', models.JSONField()),
                ('formato', models.CharField(max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vista',
                'verbose_name_plural': 'Vistas',
                'db_table': 'vistas',
            },
        ),
        migrations.CreateModel(
            name='EnvioLoteNotificaciones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('enviados', models.IntegerField(default=0)),
                ('fallidos', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('COMPLETO', 'Completo')], default='PENDIENTE', max_length=10)),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_notificaciones', to='guardias.cronogramaguardias')),
            ],
            options={
                'verbose_name': 'Envío Lote Notificaciones',
                'verbose_name_plural': 'Envíos Lote Notificaciones',
                'db_table': 'envios_lote_notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=500)),
                ('cuerpo', models.TextField()),
                ('medio', models.CharField(choices=[('EMAIL', 'Email')], default='EMAIL', max_length=10)),
                ('origen', models.CharField(choices=[('SISTEMA', 'Sistema'), ('USUARIO', 'Usuario')], max_length=10)),
                ('estado_envio', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=10)),
                ('intentos', models.IntegerField(default=0)),
                ('ultimo_intento_en', models.DateTimeField(blank=True, null=True)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to='personas.agente')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_enviadas', to='personas.agente')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reportes.plantillacorreo')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('AREA', 'Área'), ('DIRECCION', 'Dirección'), ('CONSOLIDADO', 'Consolidado')], max_length=20)),
                ('filtros', models.JSONField()),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel')], max_length=10)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('ruta_archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('estado', models.CharField(choices=[('LISTO', 'Listo'), ('ERROR', 'Error')], default='LISTO', max_length=10)),
                ('error', models.TextField(blank=True, null=True)),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_generados', to='personas.agente')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reportes',
            },
        ),
    ]
