# Generated by Django 5.2 on 2025-12-12 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('GUARDIA', 'Guardia'), ('HORA_EXTRA', 'Hora Extra'), ('INCIDENCIA', 'Incidencia'), ('ASISTENCIA', 'Asistencia'), ('USUARIO', 'Usuario'), ('LICENCIA', 'Licencia'), ('FERIADO', 'Feriado'), ('ORGANIGRAMA', 'Organigrama'), ('ROL', 'Rol'), ('LOGIN', 'Login'), ('CRONOGRAMA', 'Cronograma'), ('GENERICO', 'Generico')], default='GENERICO', max_length=50)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
