# Generated by Django 4.2.7 on 2025-12-14 22:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notificaciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificacion",
            options={
                "managed": False,
                "ordering": ["-fecha_creacion"],
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
            },
        ),
    ]
