# Generated by Django 4.2.7 on 2025-12-14 22:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notificaciones", "0002_alter_notificacion_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="notificacion",
            table="notificacion",
        ),
    ]
